language: node_js
node_js:
  - '0.10'
  - '0.11'
before_script:
  - 'gem install sass --version "=3.2.12"'
  - 'gem install compass --version "=0.12.2"'
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - ./node_modules/protractor/bin/webdriver-manager update
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: grunt travis
